#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Editors
export SHELL='zsh'
export EDITOR='vim'
export VISUAL='vim'
export GREP_OPTIONS='--color=auto' GREP_COLOR='1,32'
export PAGER='less'

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# misc
alias zshrc="vim ~/.zshrc"
alias zshenv="vim ~/.zshenv"

alias rsync-mv="rsync -a --progress --remove-source-files"
alias rsync-cp="rsync -a --progress"
alias cl='clear'

# git
alias ga='git add -A'
alias gp='git push'
alias gl='git log'
alias gs='git status'
alias gst='git st'
alias gd='git diff'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gpur='git pull --rebase'
alias gcl='git clone'
alias gta='git tag -a -m'
alias gf='git reflog'

alias glg="'C:/Program Files/TortoiseGit/bin/TortoiseGitProc.exe' /command:log /path:."

# cygwin
if [[ `uname` =~ .*CYGWIN.* ]]; then
    if [[ ( -z `/cygdrive/c/Windows/system32/whoami /priv |grep SeCreateSymbolicLinkPrivilege`) ]]; then
        echo "Warning, you do not have the SeCreateSymbolicLinkPrivilege!, cygwin will not be able to use native symlinking" 
    else
        export CYGWIN="winsymlinks:native"
    fi
    alias cyg='apt-cyg -m http://mirrors.kernel.org/sources.redhat.com/cygwin/'
    alias cygs='cygstart -- /cygdrive/c/cygwin64/setup-x86_64.exe'
    alias cyp='apt-cyg -m http://mirrors.kernel.org/sources.redhat.com/cygwinports/'
    alias cyps='cygstart -- /cygdrive/c/cygwin64/setup-x86_64.exe -K http://cygwinports.org/ports.gpg -O -s ftp://ftp.cygwinports.org/pub/cygwinports'
    alias fix-exe-perms='find . -iname "*.exe" -print0 | xargs -0 chmod 755'
fi



