#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Editors
export SHELL='zsh'
export EDITOR='vim'
export VISUAL='vim'
export GREP_OPTIONS='--color=auto' GREP_COLOR='1,32'
export PAGER='less'

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# misc
alias zshrc="vim ~/.zshrc"
alias zshenv="vim ~/.zshenv"

alias rsync-mv="rsync -a --progress --remove-source-files"
alias rsync-cp="rsync -a --progress"
alias cl='clear'

alias gtl="'C:/Program Files/TortoiseGit/bin/TortoiseGitProc.exe' /command:log /path:."
alias gtc="'C:/Program Files/TortoiseGit/bin/TortoiseGitProc.exe' /command:commit /path:."
alias gtm="'C:/Program Files/TortoiseGit/bin/TortoiseGitProc.exe' /command:merge /path:."
alias gtd="'C:/Program Files/TortoiseGit/bin/TortoiseGitProc.exe' /command:diff /path:."


# cygwin
if [[ `/usr/bin/uname` =~ .*CYGWIN.* ]]; then
    if [[ ( -z `/cygdrive/c/Windows/system32/whoami /priv |/usr/bin/grep SeCreateSymbolicLinkPrivilege`) ]]; then
        echo "Warning, you do not have the SeCreateSymbolicLinkPrivilege!, cygwin will not be able to use native symlinking" 
    else
        export CYGWIN="winsymlinks:native"
    fi
    alias cyg='apt-cyg -m http://mirrors.kernel.org/sources.redhat.com/cygwin/'
    alias cygs='cygstart -- /cygdrive/c/cygwin64/setup-x86_64.exe'
    alias cyp='apt-cyg -m http://mirrors.kernel.org/sources.redhat.com/cygwinports/'
    alias cyps='cygstart -- /cygdrive/c/cygwin64/setup-x86_64.exe -K http://cygwinports.org/ports.gpg -O -s ftp://ftp.cygwinports.org/pub/cygwinports'
    alias fix-exe-perms='find . -iname "*.exe" -print0 | xargs -0 chmod 755'
fi



